### ISSUE TITLE
Exception when formatting name of System.Array+EmptyArray<T>

### ISSUE THREAD

**Issue by stakx** [stakx/TypeNameFormatter#8]
```csharp
var type = Type.GetType("System.Array+EmptyArray`1");
Console.WriteLine(type.GetFormattedName());
```

fails with:

```
Unhandled Exception: System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at TypeNameFormatter.TypeName.AppendFormattedName(StringBuilder stringBuilder, Type type, TypeNameFormatOptions options, Type[] genericTypeArgs) in TypeName.cs:line 128
   at TypeNameFormatter.TypeName.AppendFormattedName(StringBuilder stringBuilder, Type type, TypeNameFormatOptions options, Type[] genericTypeArgs) in TypeName.cs:line 125
   at TypeNameFormatter.TypeName.AppendFormattedName(StringBuilder stringBuilder, Type type, TypeNameFormatOptions options) in TypeName.cs:line 49
   at TypeNameFormatter.TypeName.GetFormattedName(Type type, TypeNameFormatOptions options) in TypeName.cs:line 62
   at Program.Main()
```

It appears to be caused by an insufficiently accurate check added in be19c5f33b229aac087e535a100909cf67b4ee7b.

**Comment by stakx** [comment]
Fixed in c2f636ca41443dfa5ea5df5b878c7c8465e45105.
